config/routes.rb
ZhaiApp::Application.routes.draw do
  root 'stores#index'
  resources :stores
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :store
  default_scope -> { order('product_sales DESC') }
  validates :store_id, presence: true
end

app/models/store.rb
class Store < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def index
    @products=Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product=Product.find(params[:id])
    Product.find(params[:id]).destroy
    @store=@product.store
    redirect_to store_url(@store)

  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  private

    def product_params
      params.require(:product).permit(:product_name, :product_info, :product_price,:product_sales,:store_id)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def new
    @store = Store.new
  end

  def index
   @stores=Store.all
  end

  def show
    @store = Store.find(params[:id])
    @products =@store.products
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = Store.find(params[:id])
    if @store.update_attributes(store_params)
      redirect_to @store
    else
      render 'edit'
    end
  end

  def destroy
    Store.find(params[:id]).destroy
    redirect_to stores_url
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      redirect_to @store
    else
      render 'new'
    end
  end
  private

    def store_params
      params.require(:store).permit(:store_name, :store_phone, :store_info_1,:store_info_2,
:store_column_1,:store_column_2,:store_column_3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="sep20"></div>
<div class="sep20"></div>
<div class="sep20"></div>
<div class="sep20"></div>
<div class="divider ui"></div>
<div class="divider-logo">
  <img src="http://zhaime.qiniudn.com/uploads/assets/trans_logo.png">
</div>
<div class="wrap foot">
  <div class="ui three column grid">
    <div class="column">
      <div class="title">宅米</div>
      <div class="content"><a href="#">关于我们</a></div>
    </div>
    <div class="column">
      <div class="title">联系方式</div>
      <!-- <div class="content">客服：15000272097</div> -->
      <div class="content">邮箱：business@zhai.me</div>
    </div>
    <div class="column">
      <div class="title">合作伙伴</div>
      <div class="content"><a href="http://tongqu.me" target="_blank">同去网</a></div>
      <div class="content"><a href="http://isjtu.me" target="_blank">有风之南</a></div>
    </div>
  </div>
</div>
<div class="sep20"></div>
<div class="foot-wrap">
  <div>
    ©2014-2015 宅米 版权所有 沪ICP备14040291号
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="site-head">
  <div class="wrap">
    <div class="ui grid head-wrap">
      <div class="logo-wrap">
        <div class="logo">
          <a href="/" title="宅米"><img src="http://zhaime.qiniudn.com/uploads/svg/logo.svg"></a>
        </div>
      </div>
      <div class="location-wrap">

      </div>
      <div class="float-cart-wrap fly-to">
        <div>
          <span class="number" ng-style="{display:'inline'}">{{cart.number || 0}}</span>件商品 共<span class="price" ng-style="{display:'inline'}">￥{{cart.totalPrice || 0}}</span>
          <img src="http://zhaime.qiniudn.com/uploads/svg/cart_grey.svg">
        </div>
      </div>
      <div class="head-column">
        <div class="search-bar-wrap">
          <form class="ui action input search-bar" action="/search" data-method="get">
            <div class="ui icon input">
                  <input type="text" placeholder="" name="q" value="" style="padding-left:10px;">
              <i class="search icon"></i>
            </div>
          </form>
        </div>

        <div class="sign-status" signout>
          <div class="order-wrap " id="show_my_order"><span>查看订单</span></div>
          <div class="signin-wrap sign">
            <span>登录</span>
          </div>
          <div class="signup-wrap sign">
            <span>注册</span>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>
<div class="sep42">
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'/>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=07gOLO0m77P8cRs9k1IV7V7y"></script>
    <title>宅米</title>
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application",defer:"defer" ,"data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<body ng-controller="CartNewCtrl" model="$parent">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/footer' %>

  </body>
</html>

app/views/products/edit.html.erb
<h1>商品更新</h1>

<div class="ui form segment">
  <div class="ui error message">
      <div class="header">发生了错误</div>
  </div>

  <div class="span6 offset3">
    <%= form_for(@product) do |f| %>

      <%= f.label :product_name %>
      <%= f.text_field :product_name %>

      <%= f.label :store_id %>
      <%= f.text_field :store_id %>

      <%= f.label :product_info %>
      <%= f.text_field :product_info%>

      <%= f.label :product_sales %>
      <%= f.text_field :product_sales %>


      <%= f.label :product_price %>
      <%= f.text_field :product_price %>

      <%= f.submit "更新商品" %>

<% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>商品新增</h1>

<div class="ui form segment">
  <div class="ui error message">
      <div class="header">发生了错误</div>
  </div>

  <div class="span6 offset3">
    <%= form_for(@product) do |f| %>

      <%= f.label :product_name %>
      <%= f.text_field :product_name %>

      <%= f.label :store_id %>
      <%= f.text_field :store_id %>

      <%= f.label :product_info %>
      <%= f.text_field :product_info%>

      <%= f.label :product_price %>
      <%= f.text_field :product_price %>

      <%= f.label :product_sales %>
      <%= f.text_field :product_sales %>

      <%= f.submit "新增商品" %>

<% end %>
  </div>
</div>

app/views/products/show.html.erb
<h1>商品展示</h1>

<div class="ui form segment">
  <div class="ui error message">
      <div class="header">发生了错误</div>
  </div>

  <div class="span6 offset3">
    <%= form_for(@product) do |f| %>

      <%= f.label :product_name %>
      <%= f.text_field :product_name %>

      <%= f.label :store_id %>
      <%= f.text_field :store_id %>

      <%= f.label :product_info %>
      <%= f.text_field :product_info%>

      <%= f.label :product_sales %>
      <%= f.text_field :product_sales %>


      <%= f.label :product_price %>
      <%= f.text_field :product_price %>


<% end %>
  </div>
</div>

app/views/stores/edit.html.erb
<h1>店铺更新</h1>

<div class="ui form segment">
  <div class="ui error message">
      <div class="header">发生了错误</div>
  </div>

  <div class="span6 offset3">
    <%= form_for(@store) do |f| %>

      <%= f.label :store_name %>
      <%= f.text_field :store_name %>

      <%= f.label :store_phone %>
      <%= f.text_field :store_phone%>

      <%= f.label :store_info_1 %>
      <%= f.text_field :store_info_1 %>

      <%= f.label :store_info_2 %>
      <%= f.text_field :store_info_2%>

      <%= f.label :store_column_1 %>
      <%= f.text_field :store_column_1%>

      <%= f.label :store_column_2 %>
      <%= f.text_field :store_column_2%>

      <%= f.label :store_column_3 %>
      <%= f.text_field :store_column_3%>

      <%= f.submit "更新店铺" %>

<% end %>
  </div>
</div>

app/views/stores/index.html.erb
<div class="main">
  <meta name="keywords" content="宅米 宅米网 在线生活购物平台 网上便利店 网上超市 30分钟送货上门 校园超市 校园商城 校园网上超市 校园网上便利店 网上水果 O2O入口 改变生活 改变世界 社区O2O 社区生活平台"/>
<meta name="description" content="宅米（http://zhai.me）是区域化在线生活购物平台，致力于让用户的生活更便捷"/>
<div class="switch-wrap clearfix">
  <div class="flexslider">
    <ul class="slides">
          <li>
            <a href="night_cat"><img color="#151531" src="http://zhaime.qiniudn.com/uploads/activity/20150311.jpg"/></a>
          </li>
          <li>
            <a href="/store/28/637"><img color="#7FD1DD" src="http://zhaime.qiniudn.com/uploads/activity/20141216-1.png"/></a>
          </li>
          <li>
            <a href=""><img color="#DAEFDE" src="http://zhaime.qiniudn.com/uploads/activity/201411203-redo.png"/></a>
          </li>
    </ul>
  </div>
</div>
<!-- TODO:refactor this. -->
<div class="store-choose">
  <div class="wrap row1">
    <div class="ui grid catalog">
      <div class="column">
        <div class="column-underline">
          <img class="normal hide" id="0" src="http://zhaime.qiniudn.com/uploads/svg/all_inactive.svg">
          <img class="active" id="0" src="http://zhaime.qiniudn.com/uploads/svg/all_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="1" src="http://zhaime.qiniudn.com/uploads/svg/supermarket_inactive.svg">
          <img class="active hide" id="1" src="http://zhaime.qiniudn.com/uploads/svg/supermarket_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="2" src="http://zhaime.qiniudn.com/uploads/svg/breakfast_inactive.svg">
          <img class="active hide" id="2" src="http://zhaime.qiniudn.com/uploads/svg/breakfast_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="3" src="http://zhaime.qiniudn.com/uploads/svg/fruit_inactive.svg">
          <img class="active hide" id="3" src="http://zhaime.qiniudn.com/uploads/svg/fruit_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="15" src="http://zhaime.qiniudn.com/uploads/svg/night_inactive.svg">
          <img class="active hide" id="15" src="http://zhaime.qiniudn.com/uploads/svg/night_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="4" src="http://zhaime.qiniudn.com/uploads/svg/express_inactive.svg">
          <img class="active hide" id="4" src="http://zhaime.qiniudn.com/uploads/svg/express_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="5" src="http://zhaime.qiniudn.com/uploads/svg/snack_inactive.svg">
          <img class="active hide" id="5" src="http://zhaime.qiniudn.com/uploads/svg/snack_active.svg">
        </div>
      </div>
    </div>
  </div>
  <div class="wrap row2">
    <div class="ui grid catalog">
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="6" src="http://zhaime.qiniudn.com/uploads/svg/cleaning_inactive.svg">
          <img class="active hide" id="6" src="http://zhaime.qiniudn.com/uploads/svg/cleaning_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="7" src="http://zhaime.qiniudn.com/uploads/svg/food_inactive.svg">
          <img class="active hide" id="7" src="http://zhaime.qiniudn.com/uploads/svg/food_active.svg">
        </div>
      </div>
      
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="8" src="http://zhaime.qiniudn.com/uploads/svg/drink_inactive.svg">
          <img class="active hide" id="8" src="http://zhaime.qiniudn.com/uploads/svg/drink_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="9" src="http://zhaime.qiniudn.com/uploads/svg/flower_inactive.svg">
          <img class="active hide" id="9" src="http://zhaime.qiniudn.com/uploads/svg/flower_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="10" src="http://zhaime.qiniudn.com/uploads/svg/phone_inactive.svg">
          <img class="active hide" id="10" src="http://zhaime.qiniudn.com/uploads/svg/phone_active.svg">
        </div>
      </div>
<!--       <div class="column">
        <div class="column-underline">
          <img class="normal" src="http://zhaime.qiniudn.com/uploads/svg/print_inactive.svg">
          <img class="active hide" src="http://zhaime.qiniudn.com/uploads/svg/print_active.svg">
        </div>
      </div> -->
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="12" src="http://zhaime.qiniudn.com/uploads/svg/fetch_inactive.svg">
          <img class="active hide" id="12" src="http://zhaime.qiniudn.com/uploads/svg/fetch_active.svg">
        </div>
      </div>
      <div class="column">
        <div class="column-underline">
          <img class="normal" id="13" src="http://zhaime.qiniudn.com/uploads/svg/water_inactive.svg">
          <img class="active hide" id="13" src="http://zhaime.qiniudn.com/uploads/svg/water_active.svg">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wrap">
  <div class="ui grid">
    <div class="ui menu choose inverted store-choose">
      <a class="item select">
        默认排序
      </a>
      <!--       <a class="item">
              人气<i class="icon long down"></i>
            </a> -->
      <div class="item">
        <div class="ui checkbox bao">
          <input type="checkbox">
          <label>特惠中</label>
        </div>
        <div class="ui checkbox open">
          <input type="checkbox">
          <label>正在营业</label>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="store-all">
    <% @stores.each do |store|%>
    <div class="all type open">
      <%=link_to store,class:"store-open-wrap 15",target:"_blank" do%>   
     
      <div class="logo">
        <img src="http://zhaime.qiniudn.com/uploads/store/yemao_store.jpg">
      </div>
      <div class="infos">
        <div class="name"><%=store.store_name%> </div>
        <div class="info">夜宵 零食</div>
        <div class="info">
          0元起送，32种商品
        </div>
        <div class="badge-wrap">
          <span class="fu column">付</span><span class="apple column">5分钟</span><span class="new column">新</span> 
        </div>
      </div>
      <%end%>
| <%= link_to "create", new_store_path %>
| <%= link_to "retrive", store %>
| <%= link_to "update", edit_store_path(store) %>
| <%= link_to "delete", store, method: :delete,data: { confirm: "You sure?" } %>
    </div>
    <%end%>

      <div class="store-detail-wrap">
        <div>
          <!-- <div class="content">
            <i class="icon yen"></i>
            <span class="text column">起送价：欢迎光临</span>
          </div> -->
          <div class="content">
            <i class="icon rocket"></i>
            <span class="text">配送速度：5分钟</span>
          </div>
          <div class="content">
            <i class="icon time"></i>
            <span class="text">营业时间：00:00
              ~
              23:59</span>
          </div>
          <div class="ui divider"></div>
          <div class="content">
            <i class="map marker icon"></i>
            <span class="text ">店铺地址：上海交通大学</span>
          </div>
          <div class="content">
            <i class="phone icon"></i>
            <span class="text ">联系电话：13162570221</span>
          </div>
          <div class="ui divider"></div>
          <div class="content">
            <i class="icon bell outline"></i>
            <span class="text">店铺公告</span>
          </div>
          <div class="info">
            <span class="text">欢迎光临</span>
          </div>
          <div class="ui divider"></div>
          <div class="badge-wrap ui grid"><span class="fu column">付</span><span class="text column eleven wide">该店支持在线支付</span></div><div class="badge-wrap ui grid"><span class="apple column">5分钟</span><span class="text column eleven wide">该店平均送达时间约5分钟</span></div><div class="badge-wrap ui grid"><span class="new column">新</span><span class="text column eleven wide">新店上线，欢迎支持</span></div>
        </div>
      </div>

</div>

<div class="sep20"></div>
</div>


</div>
          

app/views/stores/new.html.erb
<h1>Stores#new</h1>
<p>Find me in app/views/stores/new.html.erb</p>

app/views/stores/show.html.erb
<div class="main">
  <div class="wrap">
  <div class="store-head">
    <div class="logo">
      <a href="/store/9">
        <img src="http://zhaime.qiniudn.com/uploads/store/9.jpg">
      </a>
    </div>
    <div class="store-info">
      9,交大华联二楼联通营业厅,false,0,11:00,20:30
    </div>
    <div id="store-id">9</div>
    <div class="name-wrap">
      <a class="name" id="store-name" href="/store/9">
        交大华联二楼联通营业厅
      </a>

      <div class="type">
        充值卡 路由器
      </div>
      <div class="badge-wrap">
        <span class="fu column">付</span><span class="thirty column">30分钟</span>
      </div>
    </div>
    <div class="info-wrap">
      <div class="num">30</div>
      <div class="text"><i class="icon rocket"></i>配送速度/分钟</div>
    </div>
    <div class="info-wrap">
      <div class="num" id="store-init">0</div>
      <div class="text"><i class="icon yen"></i>起送价/元</div>
    </div>
    <div class="info-wrap">
      <div class="time">
        <span id="store-start">11:00</span>~<span id="store-end">20:30</span>
      </div>
      <div class="text"><i class="icon time"></i>营业时间</div>
    </div>
    <div class="bookmark-wrap">
      <i class="icon heart empty"></i>

      <div class="text">收藏</div>
    </div>
  </div>
</div>
<div class="wrap">
  <div class="ui grid">
    <div class="column menu-wrap">
      <div class="segment">
        <div class="header">
          <a href="/store/9">
            <i class="icon block layout"></i>
            所有商品分类
          </a>
        </div>
            <div class="content" meta-id="41">
              <div class="first-catalog center">
                <a href="/store/9/41" class="">设备</a>
              </div>
              <div class="second-catalog">
              </div>
            </div>
            <div class="content" meta-id="42">
              <div class="first-catalog center">
                <a href="/store/9/42" class="">联通服务专区</a>
              </div>
              <div class="second-catalog">
              </div>
            </div>
      </div>
      <div class="sep20"></div>
      <div class="segment">
        <div class="header">
          <i class="icon bell outline"></i>
          店铺公告
        </div>
        <div class="content">
          <p>本店无特殊情况均在1h以内送到，数码物件如有缺货，时间会延长几日，欢迎来电咨询
          </p>
        </div>
        <div class="content">
          <p>店铺地址：华联2层</p>

          <p>联系电话：13162570221</p>
        </div>
        <div class="content">
          <div class="badge-wrap ui grid"><span class="fu column">付</span><span class="text column eleven wide">该店支持在线支付</span></div><div class="badge-wrap ui grid"><span class="thirty column">30分钟</span><span class="text column eleven wide">该店平均送达时间约30分钟</span></div>
        </div>
      </div>
    </div>
    <div class="column items-wrap" cart-handler>
      <div class="ui menu choose inverted" id="choose">
        <a class="item select" href="http://zhai.me/store/9">
          销量<i class="icon long down"></i>
        </a>
        <a class="item " href="http://zhai.me/store/9?&amp;type=price_down">
          价格<i class="icon sort"></i>
        </a>
        <span class="info right">
          共有商品12种
        </span>
      </div>
<% count =0 %>
<% @products.each do |product|%>
<% if count%4==0 %>
          <div class="eleven column items-wrap">

            <div class="row">
<%end%>
<div class="item-wrap" meta-id="2196" meta-imgs="">
<% count=count+1%>
  <img class="pic" src="http://zhaime.qiniudn.com/uploads/item_cover/2196.jpg">

  <div class="name">
    <%=product.product_name%>
  </div>
  <div class="price">
    <i class="icon yen"></i><span>99.0</span>
  </div>
  <div class="message">
      300M急速网络

  </div>
  <div class="buy">
    <div class="btn">
      <div>
        <span>加入购物车</span>
        <img class="cart" src="http://zhaime.qiniudn.com/uploads/svg/cart_white.svg">
      </div>
    </div>
    <div class="number">
      <input value="0" maxlength="2">
    </div>
    <div class="minus">
      <div>
        —
      </div>
    </div>
  </div>
| <%= link_to "create", new_product_path %>
| <%= link_to "retrive", product %>
| <%= link_to "update", edit_product_path(product) %>
| <%= link_to "delete", product, method: :delete,data: { confirm: "You sure?" } %>
</div>

<% if count%4==0 %>
            </div>

          </div>
<%end%>


<%end%>
 
</div>
</div>
</div>
</div>
</div>
</div>